
rm -rf CMakeCache.txt
rm -rf CMakeFiles

cmake -DCMAKE_BUILD_TYPE=Debug -DDAVISFX3=1 -DDAVISFX2=0 -DENABLE_FILE_INPUT=0 -DENABLE_STATISTICS=1 -DENABLE_BAFILTER=1 -DENABLE_VISUALIZER=1 -DENABLE_CAMERACALIBRATION=1 -DENABLE_IMAGEGENERATOR=0 -DENABLE_CAFFEINTERFACE=0 -DENABLE_MULTICAMERACALIBRATION=1     

#make -j 4
