
rm -rf CMakeCache
rm -rf CMakeFiles

cmake -DDAVISFX3=1 -DDAVISFX2=0 -DENABLE_FILE_INPUT=0 -DENABLE_STATISTICS=1 -DENABLE_BAFILTER=1 -DENABLE_VISUALIZER=1 -DENABLE_IMAGEGENERATOR=1 -DENABLE_CAMERACALIBRATION=0 -DENABLE_CAFFEINTERFACE=1 -DENABLE_IMAGESTREAMERBEEPER=1 -DCaffe_DIR=/media/federico/space/inilabs/3rdparty/caffe/ -DCPU_ONLY=1   

#make -j 4
